// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v4.25.1
// source: proto/osmanage.proto

package osmanage

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	OsmanageService_SetupInstance_FullMethodName                        = "/osmanage.OsmanageService/SetupInstance"
	OsmanageService_ConfigInstance_FullMethodName                       = "/osmanage.OsmanageService/ConfigInstance"
	OsmanageService_CreateInstance_FullMethodName                       = "/osmanage.OsmanageService/CreateInstance"
	OsmanageService_RemoveInstance_FullMethodName                       = "/osmanage.OsmanageService/RemoveInstance"
	OsmanageService_GetNamespaceExists_FullMethodName                   = "/osmanage.OsmanageService/GetNamespaceExists"
	OsmanageService_GetClusterStatus_FullMethodName                     = "/osmanage.OsmanageService/GetClusterStatus"
	OsmanageService_GetServiceAddress_FullMethodName                    = "/osmanage.OsmanageService/GetServiceAddress"
	OsmanageService_GetInstanceHealth_FullMethodName                    = "/osmanage.OsmanageService/GetInstanceHealth"
	OsmanageService_GetInstanceStatus_FullMethodName                    = "/osmanage.OsmanageService/GetInstanceStatus"
	OsmanageService_UpdateBackendmanage_FullMethodName                  = "/osmanage.OsmanageService/UpdateBackendmanage"
	OsmanageService_UpdateInstance_FullMethodName                       = "/osmanage.OsmanageService/UpdateInstance"
	OsmanageService_ScaleService_FullMethodName                         = "/osmanage.OsmanageService/ScaleService"
	OsmanageService_StartInstance_FullMethodName                        = "/osmanage.OsmanageService/StartInstance"
	OsmanageService_StopInstance_FullMethodName                         = "/osmanage.OsmanageService/StopInstance"
	OsmanageService_GetCollection_FullMethodName                        = "/osmanage.OsmanageService/GetCollection"
	OsmanageService_MigrationsMigrate_FullMethodName                    = "/osmanage.OsmanageService/MigrationsMigrate"
	OsmanageService_MigrationsFinalize_FullMethodName                   = "/osmanage.OsmanageService/MigrationsFinalize"
	OsmanageService_MigrationsReset_FullMethodName                      = "/osmanage.OsmanageService/MigrationsReset"
	OsmanageService_MigrationsClearCollectionfieldTables_FullMethodName = "/osmanage.OsmanageService/MigrationsClearCollectionfieldTables"
	OsmanageService_MigrationsStats_FullMethodName                      = "/osmanage.OsmanageService/MigrationsStats"
	OsmanageService_MigrationsProgress_FullMethodName                   = "/osmanage.OsmanageService/MigrationsProgress"
	OsmanageService_SendManageAction_FullMethodName                     = "/osmanage.OsmanageService/SendManageAction"
)

// OsmanageServiceClient is the client API for OsmanageService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type OsmanageServiceClient interface {
	// Instance filesystem operations
	SetupInstance(ctx context.Context, in *InstanceConfigRequest, opts ...grpc.CallOption) (*InstanceConfigResponse, error)
	ConfigInstance(ctx context.Context, in *InstanceConfigRequest, opts ...grpc.CallOption) (*InstanceConfigResponse, error)
	CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error)
	RemoveInstance(ctx context.Context, in *RemoveInstanceRequest, opts ...grpc.CallOption) (*RemoveInstanceResponse, error)
	// k8s actions
	GetNamespaceExists(ctx context.Context, in *GetNamespaceExistsRequest, opts ...grpc.CallOption) (*GetNamespaceExistsResponse, error)
	GetClusterStatus(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*GetClusterStatusResponse, error)
	GetServiceAddress(ctx context.Context, in *GetServiceAddressRequest, opts ...grpc.CallOption) (*GetServiceAddressResponse, error)
	GetInstanceHealth(ctx context.Context, in *GetInstanceHealthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetInstanceHealthResponse], error)
	GetInstanceStatus(ctx context.Context, in *GetInstanceStatusRequest, opts ...grpc.CallOption) (*GetInstanceStatusResponse, error)
	UpdateBackendmanage(ctx context.Context, in *UpdateBackendmanageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpdateBackendmanageResponse], error)
	UpdateInstance(ctx context.Context, in *UpdateInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpdateInstanceResponse], error)
	ScaleService(ctx context.Context, in *ScaleServiceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScaleServiceResponse], error)
	StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StartInstanceResponse], error)
	StopInstance(ctx context.Context, in *StopInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StopInstanceResponse], error)
	// datastore query action (via openslides-go)
	GetCollection(ctx context.Context, in *GetCollectionRequest, opts ...grpc.CallOption) (*GetCollectionResponse, error)
	// server side streaming
	MigrationsMigrate(ctx context.Context, in *MigrationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MigrationsProgressResponse], error)
	MigrationsFinalize(ctx context.Context, in *MigrationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MigrationsProgressResponse], error)
	// unary gRPC calls
	MigrationsReset(ctx context.Context, in *MigrationsRequest, opts ...grpc.CallOption) (*MigrationsResponse, error)
	MigrationsClearCollectionfieldTables(ctx context.Context, in *MigrationsRequest, opts ...grpc.CallOption) (*MigrationsResponse, error)
	MigrationsStats(ctx context.Context, in *MigrationsRequest, opts ...grpc.CallOption) (*MigrationsResponse, error)
	MigrationsProgress(ctx context.Context, in *MigrationsRequest, opts ...grpc.CallOption) (*MigrationsResponse, error)
	// generic manage action via backendmanage client
	SendManageAction(ctx context.Context, in *SendManageActionRequest, opts ...grpc.CallOption) (*SendManageActionResponse, error)
}

type osmanageServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewOsmanageServiceClient(cc grpc.ClientConnInterface) OsmanageServiceClient {
	return &osmanageServiceClient{cc}
}

func (c *osmanageServiceClient) SetupInstance(ctx context.Context, in *InstanceConfigRequest, opts ...grpc.CallOption) (*InstanceConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceConfigResponse)
	err := c.cc.Invoke(ctx, OsmanageService_SetupInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osmanageServiceClient) ConfigInstance(ctx context.Context, in *InstanceConfigRequest, opts ...grpc.CallOption) (*InstanceConfigResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InstanceConfigResponse)
	err := c.cc.Invoke(ctx, OsmanageService_ConfigInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osmanageServiceClient) CreateInstance(ctx context.Context, in *CreateInstanceRequest, opts ...grpc.CallOption) (*CreateInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateInstanceResponse)
	err := c.cc.Invoke(ctx, OsmanageService_CreateInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osmanageServiceClient) RemoveInstance(ctx context.Context, in *RemoveInstanceRequest, opts ...grpc.CallOption) (*RemoveInstanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveInstanceResponse)
	err := c.cc.Invoke(ctx, OsmanageService_RemoveInstance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osmanageServiceClient) GetNamespaceExists(ctx context.Context, in *GetNamespaceExistsRequest, opts ...grpc.CallOption) (*GetNamespaceExistsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetNamespaceExistsResponse)
	err := c.cc.Invoke(ctx, OsmanageService_GetNamespaceExists_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osmanageServiceClient) GetClusterStatus(ctx context.Context, in *GetClusterStatusRequest, opts ...grpc.CallOption) (*GetClusterStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetClusterStatusResponse)
	err := c.cc.Invoke(ctx, OsmanageService_GetClusterStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osmanageServiceClient) GetServiceAddress(ctx context.Context, in *GetServiceAddressRequest, opts ...grpc.CallOption) (*GetServiceAddressResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetServiceAddressResponse)
	err := c.cc.Invoke(ctx, OsmanageService_GetServiceAddress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osmanageServiceClient) GetInstanceHealth(ctx context.Context, in *GetInstanceHealthRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[GetInstanceHealthResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OsmanageService_ServiceDesc.Streams[0], OsmanageService_GetInstanceHealth_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[GetInstanceHealthRequest, GetInstanceHealthResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OsmanageService_GetInstanceHealthClient = grpc.ServerStreamingClient[GetInstanceHealthResponse]

func (c *osmanageServiceClient) GetInstanceStatus(ctx context.Context, in *GetInstanceStatusRequest, opts ...grpc.CallOption) (*GetInstanceStatusResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInstanceStatusResponse)
	err := c.cc.Invoke(ctx, OsmanageService_GetInstanceStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osmanageServiceClient) UpdateBackendmanage(ctx context.Context, in *UpdateBackendmanageRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpdateBackendmanageResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OsmanageService_ServiceDesc.Streams[1], OsmanageService_UpdateBackendmanage_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpdateBackendmanageRequest, UpdateBackendmanageResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OsmanageService_UpdateBackendmanageClient = grpc.ServerStreamingClient[UpdateBackendmanageResponse]

func (c *osmanageServiceClient) UpdateInstance(ctx context.Context, in *UpdateInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[UpdateInstanceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OsmanageService_ServiceDesc.Streams[2], OsmanageService_UpdateInstance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[UpdateInstanceRequest, UpdateInstanceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OsmanageService_UpdateInstanceClient = grpc.ServerStreamingClient[UpdateInstanceResponse]

func (c *osmanageServiceClient) ScaleService(ctx context.Context, in *ScaleServiceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ScaleServiceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OsmanageService_ServiceDesc.Streams[3], OsmanageService_ScaleService_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ScaleServiceRequest, ScaleServiceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OsmanageService_ScaleServiceClient = grpc.ServerStreamingClient[ScaleServiceResponse]

func (c *osmanageServiceClient) StartInstance(ctx context.Context, in *StartInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StartInstanceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OsmanageService_ServiceDesc.Streams[4], OsmanageService_StartInstance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StartInstanceRequest, StartInstanceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OsmanageService_StartInstanceClient = grpc.ServerStreamingClient[StartInstanceResponse]

func (c *osmanageServiceClient) StopInstance(ctx context.Context, in *StopInstanceRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[StopInstanceResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OsmanageService_ServiceDesc.Streams[5], OsmanageService_StopInstance_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[StopInstanceRequest, StopInstanceResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OsmanageService_StopInstanceClient = grpc.ServerStreamingClient[StopInstanceResponse]

func (c *osmanageServiceClient) GetCollection(ctx context.Context, in *GetCollectionRequest, opts ...grpc.CallOption) (*GetCollectionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCollectionResponse)
	err := c.cc.Invoke(ctx, OsmanageService_GetCollection_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osmanageServiceClient) MigrationsMigrate(ctx context.Context, in *MigrationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MigrationsProgressResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OsmanageService_ServiceDesc.Streams[6], OsmanageService_MigrationsMigrate_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MigrationsRequest, MigrationsProgressResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OsmanageService_MigrationsMigrateClient = grpc.ServerStreamingClient[MigrationsProgressResponse]

func (c *osmanageServiceClient) MigrationsFinalize(ctx context.Context, in *MigrationsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[MigrationsProgressResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &OsmanageService_ServiceDesc.Streams[7], OsmanageService_MigrationsFinalize_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[MigrationsRequest, MigrationsProgressResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OsmanageService_MigrationsFinalizeClient = grpc.ServerStreamingClient[MigrationsProgressResponse]

func (c *osmanageServiceClient) MigrationsReset(ctx context.Context, in *MigrationsRequest, opts ...grpc.CallOption) (*MigrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationsResponse)
	err := c.cc.Invoke(ctx, OsmanageService_MigrationsReset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osmanageServiceClient) MigrationsClearCollectionfieldTables(ctx context.Context, in *MigrationsRequest, opts ...grpc.CallOption) (*MigrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationsResponse)
	err := c.cc.Invoke(ctx, OsmanageService_MigrationsClearCollectionfieldTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osmanageServiceClient) MigrationsStats(ctx context.Context, in *MigrationsRequest, opts ...grpc.CallOption) (*MigrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationsResponse)
	err := c.cc.Invoke(ctx, OsmanageService_MigrationsStats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osmanageServiceClient) MigrationsProgress(ctx context.Context, in *MigrationsRequest, opts ...grpc.CallOption) (*MigrationsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MigrationsResponse)
	err := c.cc.Invoke(ctx, OsmanageService_MigrationsProgress_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *osmanageServiceClient) SendManageAction(ctx context.Context, in *SendManageActionRequest, opts ...grpc.CallOption) (*SendManageActionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SendManageActionResponse)
	err := c.cc.Invoke(ctx, OsmanageService_SendManageAction_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// OsmanageServiceServer is the server API for OsmanageService service.
// All implementations must embed UnimplementedOsmanageServiceServer
// for forward compatibility.
type OsmanageServiceServer interface {
	// Instance filesystem operations
	SetupInstance(context.Context, *InstanceConfigRequest) (*InstanceConfigResponse, error)
	ConfigInstance(context.Context, *InstanceConfigRequest) (*InstanceConfigResponse, error)
	CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error)
	RemoveInstance(context.Context, *RemoveInstanceRequest) (*RemoveInstanceResponse, error)
	// k8s actions
	GetNamespaceExists(context.Context, *GetNamespaceExistsRequest) (*GetNamespaceExistsResponse, error)
	GetClusterStatus(context.Context, *GetClusterStatusRequest) (*GetClusterStatusResponse, error)
	GetServiceAddress(context.Context, *GetServiceAddressRequest) (*GetServiceAddressResponse, error)
	GetInstanceHealth(*GetInstanceHealthRequest, grpc.ServerStreamingServer[GetInstanceHealthResponse]) error
	GetInstanceStatus(context.Context, *GetInstanceStatusRequest) (*GetInstanceStatusResponse, error)
	UpdateBackendmanage(*UpdateBackendmanageRequest, grpc.ServerStreamingServer[UpdateBackendmanageResponse]) error
	UpdateInstance(*UpdateInstanceRequest, grpc.ServerStreamingServer[UpdateInstanceResponse]) error
	ScaleService(*ScaleServiceRequest, grpc.ServerStreamingServer[ScaleServiceResponse]) error
	StartInstance(*StartInstanceRequest, grpc.ServerStreamingServer[StartInstanceResponse]) error
	StopInstance(*StopInstanceRequest, grpc.ServerStreamingServer[StopInstanceResponse]) error
	// datastore query action (via openslides-go)
	GetCollection(context.Context, *GetCollectionRequest) (*GetCollectionResponse, error)
	// server side streaming
	MigrationsMigrate(*MigrationsRequest, grpc.ServerStreamingServer[MigrationsProgressResponse]) error
	MigrationsFinalize(*MigrationsRequest, grpc.ServerStreamingServer[MigrationsProgressResponse]) error
	// unary gRPC calls
	MigrationsReset(context.Context, *MigrationsRequest) (*MigrationsResponse, error)
	MigrationsClearCollectionfieldTables(context.Context, *MigrationsRequest) (*MigrationsResponse, error)
	MigrationsStats(context.Context, *MigrationsRequest) (*MigrationsResponse, error)
	MigrationsProgress(context.Context, *MigrationsRequest) (*MigrationsResponse, error)
	// generic manage action via backendmanage client
	SendManageAction(context.Context, *SendManageActionRequest) (*SendManageActionResponse, error)
	mustEmbedUnimplementedOsmanageServiceServer()
}

// UnimplementedOsmanageServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedOsmanageServiceServer struct{}

func (UnimplementedOsmanageServiceServer) SetupInstance(context.Context, *InstanceConfigRequest) (*InstanceConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetupInstance not implemented")
}
func (UnimplementedOsmanageServiceServer) ConfigInstance(context.Context, *InstanceConfigRequest) (*InstanceConfigResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ConfigInstance not implemented")
}
func (UnimplementedOsmanageServiceServer) CreateInstance(context.Context, *CreateInstanceRequest) (*CreateInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateInstance not implemented")
}
func (UnimplementedOsmanageServiceServer) RemoveInstance(context.Context, *RemoveInstanceRequest) (*RemoveInstanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveInstance not implemented")
}
func (UnimplementedOsmanageServiceServer) GetNamespaceExists(context.Context, *GetNamespaceExistsRequest) (*GetNamespaceExistsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetNamespaceExists not implemented")
}
func (UnimplementedOsmanageServiceServer) GetClusterStatus(context.Context, *GetClusterStatusRequest) (*GetClusterStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetClusterStatus not implemented")
}
func (UnimplementedOsmanageServiceServer) GetServiceAddress(context.Context, *GetServiceAddressRequest) (*GetServiceAddressResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetServiceAddress not implemented")
}
func (UnimplementedOsmanageServiceServer) GetInstanceHealth(*GetInstanceHealthRequest, grpc.ServerStreamingServer[GetInstanceHealthResponse]) error {
	return status.Error(codes.Unimplemented, "method GetInstanceHealth not implemented")
}
func (UnimplementedOsmanageServiceServer) GetInstanceStatus(context.Context, *GetInstanceStatusRequest) (*GetInstanceStatusResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInstanceStatus not implemented")
}
func (UnimplementedOsmanageServiceServer) UpdateBackendmanage(*UpdateBackendmanageRequest, grpc.ServerStreamingServer[UpdateBackendmanageResponse]) error {
	return status.Error(codes.Unimplemented, "method UpdateBackendmanage not implemented")
}
func (UnimplementedOsmanageServiceServer) UpdateInstance(*UpdateInstanceRequest, grpc.ServerStreamingServer[UpdateInstanceResponse]) error {
	return status.Error(codes.Unimplemented, "method UpdateInstance not implemented")
}
func (UnimplementedOsmanageServiceServer) ScaleService(*ScaleServiceRequest, grpc.ServerStreamingServer[ScaleServiceResponse]) error {
	return status.Error(codes.Unimplemented, "method ScaleService not implemented")
}
func (UnimplementedOsmanageServiceServer) StartInstance(*StartInstanceRequest, grpc.ServerStreamingServer[StartInstanceResponse]) error {
	return status.Error(codes.Unimplemented, "method StartInstance not implemented")
}
func (UnimplementedOsmanageServiceServer) StopInstance(*StopInstanceRequest, grpc.ServerStreamingServer[StopInstanceResponse]) error {
	return status.Error(codes.Unimplemented, "method StopInstance not implemented")
}
func (UnimplementedOsmanageServiceServer) GetCollection(context.Context, *GetCollectionRequest) (*GetCollectionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCollection not implemented")
}
func (UnimplementedOsmanageServiceServer) MigrationsMigrate(*MigrationsRequest, grpc.ServerStreamingServer[MigrationsProgressResponse]) error {
	return status.Error(codes.Unimplemented, "method MigrationsMigrate not implemented")
}
func (UnimplementedOsmanageServiceServer) MigrationsFinalize(*MigrationsRequest, grpc.ServerStreamingServer[MigrationsProgressResponse]) error {
	return status.Error(codes.Unimplemented, "method MigrationsFinalize not implemented")
}
func (UnimplementedOsmanageServiceServer) MigrationsReset(context.Context, *MigrationsRequest) (*MigrationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrationsReset not implemented")
}
func (UnimplementedOsmanageServiceServer) MigrationsClearCollectionfieldTables(context.Context, *MigrationsRequest) (*MigrationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrationsClearCollectionfieldTables not implemented")
}
func (UnimplementedOsmanageServiceServer) MigrationsStats(context.Context, *MigrationsRequest) (*MigrationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrationsStats not implemented")
}
func (UnimplementedOsmanageServiceServer) MigrationsProgress(context.Context, *MigrationsRequest) (*MigrationsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MigrationsProgress not implemented")
}
func (UnimplementedOsmanageServiceServer) SendManageAction(context.Context, *SendManageActionRequest) (*SendManageActionResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SendManageAction not implemented")
}
func (UnimplementedOsmanageServiceServer) mustEmbedUnimplementedOsmanageServiceServer() {}
func (UnimplementedOsmanageServiceServer) testEmbeddedByValue()                         {}

// UnsafeOsmanageServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to OsmanageServiceServer will
// result in compilation errors.
type UnsafeOsmanageServiceServer interface {
	mustEmbedUnimplementedOsmanageServiceServer()
}

func RegisterOsmanageServiceServer(s grpc.ServiceRegistrar, srv OsmanageServiceServer) {
	// If the following call panics, it indicates UnimplementedOsmanageServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&OsmanageService_ServiceDesc, srv)
}

func _OsmanageService_SetupInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsmanageServiceServer).SetupInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OsmanageService_SetupInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsmanageServiceServer).SetupInstance(ctx, req.(*InstanceConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsmanageService_ConfigInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InstanceConfigRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsmanageServiceServer).ConfigInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OsmanageService_ConfigInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsmanageServiceServer).ConfigInstance(ctx, req.(*InstanceConfigRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsmanageService_CreateInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsmanageServiceServer).CreateInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OsmanageService_CreateInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsmanageServiceServer).CreateInstance(ctx, req.(*CreateInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsmanageService_RemoveInstance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveInstanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsmanageServiceServer).RemoveInstance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OsmanageService_RemoveInstance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsmanageServiceServer).RemoveInstance(ctx, req.(*RemoveInstanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsmanageService_GetNamespaceExists_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetNamespaceExistsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsmanageServiceServer).GetNamespaceExists(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OsmanageService_GetNamespaceExists_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsmanageServiceServer).GetNamespaceExists(ctx, req.(*GetNamespaceExistsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsmanageService_GetClusterStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetClusterStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsmanageServiceServer).GetClusterStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OsmanageService_GetClusterStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsmanageServiceServer).GetClusterStatus(ctx, req.(*GetClusterStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsmanageService_GetServiceAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetServiceAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsmanageServiceServer).GetServiceAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OsmanageService_GetServiceAddress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsmanageServiceServer).GetServiceAddress(ctx, req.(*GetServiceAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsmanageService_GetInstanceHealth_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(GetInstanceHealthRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OsmanageServiceServer).GetInstanceHealth(m, &grpc.GenericServerStream[GetInstanceHealthRequest, GetInstanceHealthResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OsmanageService_GetInstanceHealthServer = grpc.ServerStreamingServer[GetInstanceHealthResponse]

func _OsmanageService_GetInstanceStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInstanceStatusRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsmanageServiceServer).GetInstanceStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OsmanageService_GetInstanceStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsmanageServiceServer).GetInstanceStatus(ctx, req.(*GetInstanceStatusRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsmanageService_UpdateBackendmanage_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UpdateBackendmanageRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OsmanageServiceServer).UpdateBackendmanage(m, &grpc.GenericServerStream[UpdateBackendmanageRequest, UpdateBackendmanageResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OsmanageService_UpdateBackendmanageServer = grpc.ServerStreamingServer[UpdateBackendmanageResponse]

func _OsmanageService_UpdateInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(UpdateInstanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OsmanageServiceServer).UpdateInstance(m, &grpc.GenericServerStream[UpdateInstanceRequest, UpdateInstanceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OsmanageService_UpdateInstanceServer = grpc.ServerStreamingServer[UpdateInstanceResponse]

func _OsmanageService_ScaleService_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ScaleServiceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OsmanageServiceServer).ScaleService(m, &grpc.GenericServerStream[ScaleServiceRequest, ScaleServiceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OsmanageService_ScaleServiceServer = grpc.ServerStreamingServer[ScaleServiceResponse]

func _OsmanageService_StartInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StartInstanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OsmanageServiceServer).StartInstance(m, &grpc.GenericServerStream[StartInstanceRequest, StartInstanceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OsmanageService_StartInstanceServer = grpc.ServerStreamingServer[StartInstanceResponse]

func _OsmanageService_StopInstance_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(StopInstanceRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OsmanageServiceServer).StopInstance(m, &grpc.GenericServerStream[StopInstanceRequest, StopInstanceResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OsmanageService_StopInstanceServer = grpc.ServerStreamingServer[StopInstanceResponse]

func _OsmanageService_GetCollection_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCollectionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsmanageServiceServer).GetCollection(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OsmanageService_GetCollection_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsmanageServiceServer).GetCollection(ctx, req.(*GetCollectionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsmanageService_MigrationsMigrate_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MigrationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OsmanageServiceServer).MigrationsMigrate(m, &grpc.GenericServerStream[MigrationsRequest, MigrationsProgressResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OsmanageService_MigrationsMigrateServer = grpc.ServerStreamingServer[MigrationsProgressResponse]

func _OsmanageService_MigrationsFinalize_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(MigrationsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(OsmanageServiceServer).MigrationsFinalize(m, &grpc.GenericServerStream[MigrationsRequest, MigrationsProgressResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type OsmanageService_MigrationsFinalizeServer = grpc.ServerStreamingServer[MigrationsProgressResponse]

func _OsmanageService_MigrationsReset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsmanageServiceServer).MigrationsReset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OsmanageService_MigrationsReset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsmanageServiceServer).MigrationsReset(ctx, req.(*MigrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsmanageService_MigrationsClearCollectionfieldTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsmanageServiceServer).MigrationsClearCollectionfieldTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OsmanageService_MigrationsClearCollectionfieldTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsmanageServiceServer).MigrationsClearCollectionfieldTables(ctx, req.(*MigrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsmanageService_MigrationsStats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsmanageServiceServer).MigrationsStats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OsmanageService_MigrationsStats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsmanageServiceServer).MigrationsStats(ctx, req.(*MigrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsmanageService_MigrationsProgress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MigrationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsmanageServiceServer).MigrationsProgress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OsmanageService_MigrationsProgress_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsmanageServiceServer).MigrationsProgress(ctx, req.(*MigrationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _OsmanageService_SendManageAction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendManageActionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(OsmanageServiceServer).SendManageAction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: OsmanageService_SendManageAction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(OsmanageServiceServer).SendManageAction(ctx, req.(*SendManageActionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// OsmanageService_ServiceDesc is the grpc.ServiceDesc for OsmanageService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var OsmanageService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "osmanage.OsmanageService",
	HandlerType: (*OsmanageServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SetupInstance",
			Handler:    _OsmanageService_SetupInstance_Handler,
		},
		{
			MethodName: "ConfigInstance",
			Handler:    _OsmanageService_ConfigInstance_Handler,
		},
		{
			MethodName: "CreateInstance",
			Handler:    _OsmanageService_CreateInstance_Handler,
		},
		{
			MethodName: "RemoveInstance",
			Handler:    _OsmanageService_RemoveInstance_Handler,
		},
		{
			MethodName: "GetNamespaceExists",
			Handler:    _OsmanageService_GetNamespaceExists_Handler,
		},
		{
			MethodName: "GetClusterStatus",
			Handler:    _OsmanageService_GetClusterStatus_Handler,
		},
		{
			MethodName: "GetServiceAddress",
			Handler:    _OsmanageService_GetServiceAddress_Handler,
		},
		{
			MethodName: "GetInstanceStatus",
			Handler:    _OsmanageService_GetInstanceStatus_Handler,
		},
		{
			MethodName: "GetCollection",
			Handler:    _OsmanageService_GetCollection_Handler,
		},
		{
			MethodName: "MigrationsReset",
			Handler:    _OsmanageService_MigrationsReset_Handler,
		},
		{
			MethodName: "MigrationsClearCollectionfieldTables",
			Handler:    _OsmanageService_MigrationsClearCollectionfieldTables_Handler,
		},
		{
			MethodName: "MigrationsStats",
			Handler:    _OsmanageService_MigrationsStats_Handler,
		},
		{
			MethodName: "MigrationsProgress",
			Handler:    _OsmanageService_MigrationsProgress_Handler,
		},
		{
			MethodName: "SendManageAction",
			Handler:    _OsmanageService_SendManageAction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "GetInstanceHealth",
			Handler:       _OsmanageService_GetInstanceHealth_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdateBackendmanage",
			Handler:       _OsmanageService_UpdateBackendmanage_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "UpdateInstance",
			Handler:       _OsmanageService_UpdateInstance_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ScaleService",
			Handler:       _OsmanageService_ScaleService_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StartInstance",
			Handler:       _OsmanageService_StartInstance_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "StopInstance",
			Handler:       _OsmanageService_StopInstance_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MigrationsMigrate",
			Handler:       _OsmanageService_MigrationsMigrate_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "MigrationsFinalize",
			Handler:       _OsmanageService_MigrationsFinalize_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/osmanage.proto",
}
